name: mongo

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: atok
      MONGO_INITDB_ROOT_PASSWORD: Atok1915
    networks:
      - mognonetwork

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: atok
      ME_CONFIG_MONGODB_ADMINPASSWORD: Atok1915
      ME_CONFIG_MONGODB_URL: mongodb://atok:Atok1915@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - mognonetwork

networks:
  mognonetwork:
    driver: bridge

volumes:
  db_data:
