name: mongo

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ikmal3499
      MONGO_INITDB_ROOT_PASSWORD: Ikmalakmal3499
    networks:
      - mognonetwork

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ikmal3499
      ME_CONFIG_MONGODB_ADMINPASSWORD: Ikmalakmal3499
      ME_CONFIG_MONGODB_URL: mongodb://ikmal3499:Ikmalakmal3499@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - mognonetwork

networks:
  mognonetwork:
    driver: bridge

volumes:
  db_data:
